services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: mysql
    network_mode: "host"
    
  code:
    image: python
    network_mode: "host"
    container_name: code
    depends_on:
      - db
    volumes:
      - ./app:/app
    working_dir: /app
    command: >
      sh -c "pip install --upgrade pip &&
             pip install -r requirements.txt &&
             python main.py"

networks:
  host:
    name: host
    external: true